### PR TITLE
Updated README.md example with a currently working one.

### LINKED ISSUE #15: Example code from README.md doesn't compile
The example code showed in the README.md doesn't compile under the GHC version 7.10.3.

Give several errors as:

> Couldn't match type ‘Char’ with ‘[Char]’
Expected type: [String]
  Actual type: [Char]
In the second argument of ‘(:=>)’, namely ‘"hello there"’
In the expression: Baz :=> "hello there"
In the first argument of ‘fromList’, namely
  ‘[Foo :=> pi, Baz :=> "hello there"]’
/home/osboxes/Documents/Haskell-Workshop/app/Main.hs: 6, 19

>No instance for (Num [Int]) arising from the literal ‘42’
In the second argument of ‘singleton’, namely ‘42’
In the expression: singleton Bar 42
In an equation for ‘y’: y = singleton Bar 42
/home/osboxes/Documents/Haskell-Workshop/app/Main.hs: 15, 20

>Couldn't match type ‘v’ with ‘[v]’
  ‘v’ is a rigid type variable bound by
      a type expected by the context: Foo v -> [v] -> [v] -> [v]
      at app/Main.hs:15:7
Expected type: Foo v -> [v] -> [v] -> [v]
  Actual type: Foo [v] -> [v] -> [v] -> [v]
In the first argument of ‘unionWithKey’, namely ‘addFoo’
In the expression: unionWithKey addFoo x z

### PR DESCRIPTION
**Pull request by JavierJF**
Fixes #15 .

### CODE REVIEW

**Comment by chshersh** [comment]
Any news on merging this to `master` or/and resolving conflicts? I would love to use `dependent-map` package but I find lack of documentation frustrating...

**Comment by ryantrinkle** [comment]
@JavierJF Would you mind updating this so that it merges cleanly against the current master?

**Comment by JavierJF** [comment]
Of course, I will update it soon. Thanks you.

**Comment by Wizek** [comment]
Any updates on this? I'm also trying to try this package without much success yet.

Also, where can I find the FooGADT module? Shouldn't its content be inlined into the readme for a self-contained example?

cc @JavierJF

**Comment by Wizek** [comment]
Together with @vaibhavsagar, earlier today we were able to make some sense of this package. Here is a small, self-contained, compiling (as of latest, 0.2.4.0) example that we got to:

```hs
{-# language GADTs #-}
{-# language DeriveGeneric #-}
{-# language DeriveAnyClass #-}
{-# language TemplateHaskell #-}
{-# language StandaloneDeriving #-}

import Prelude                  (Int, String, print, ($))
import Data.GADT.Show           ()
import Data.GADT.Compare        ()
import Data.Dependent.Map       (DMap, fromList, (!))
import Data.Dependent.Sum       ((==>))
import Data.GADT.Compare.TH     (deriveGEq, deriveGCompare)
import Data.Functor.Identity    (Identity)

data Foo a where
  AnInt   :: Foo Int
  AString :: Foo String

deriveGEq      ''Foo
deriveGCompare ''Foo

dmap1 :: DMap Foo Identity
dmap1 = fromList [AnInt ==> 1, AString ==> "bar"]

main = do
  print $ dmap1 ! AnInt
  print $ dmap1 ! AString

  -- Prints:
  -- Identity 1
  -- Identity "bar"
```

It might make sense to put this into the readme and/or hackage/haddocs.

(`Show`ability (e.g. `print $ fromList [AnInt ==> 1]`) is still a mystery to us.)

Edit: Included explicit imports to further improve understandability.

**Comment by 3noch** [comment]
I've updated the README to a working example.

**Pull request closed without merging**
