### PR TITLE
fix cabal file for ghc-7.8.4

### PR DESCRIPTION
**Pull request by s9gf4ult**

### CODE REVIEW

**Comment by mokus0** [comment]
based on a tip from Carter Schonwald, I've set up a multi-ghc travis build to help narrow down this problem.  It appears to actually be related to cabal version rather than ghc version, and this fix is at least partially backward compatible.  Gonna go ahead and merge it and see what the buildbot says about it.

**Comment by s9gf4ult** [comment]
I can surely say, that cabal-1.22 and ghc-7.8 are not compatible with current version. 

If this patch is not backward compatible then maybe major version should be changed with dependencies constraints ... or something like that.

**Comment by mokus0** [comment]
It turned out the syntax you switched to is supported by older Cabal versions as well.  This is now on Hackage as 0.1.1.3

**Comment by s9gf4ult** [comment]
Great, thanks!

**Pull request merged**
