### PR TITLE
Get rid of *Tag classes

### PR DESCRIPTION
**Pull request by Ericson2314**
Depends on mokus0/dependent-sum#23. Also should depend on getting rid of GHC <8 support in this repo.

### CODE REVIEW

**Comment by Ericson2314** [comment]
CC @cgibbard

**Comment by treeowl** [comment]
It's really hard to see the meat of this PR. Could you maybe squash some commits, leaving the whitespace commit separate?

**Comment by ali-abrar** [comment]
> Depends on [mokus0/dependent-sum#23](https://github.com/mokus0/dependent-sum/pull/23). Also should depend on getting rid of GHC <8 support in this repo.

That's been merged and released as [dependent-sum-0.6](https://hackage.haskell.org/package/dependent-sum-0.6)

**Comment by ali-abrar** [comment]
> It's really hard to see the meat of this PR. Could you maybe squash some commits, leaving the whitespace commit separate?

You can select a range of commits excluding the whitespace commit. Here's the [result](https://github.com/mokus0/dependent-map/pull/26/files/f315e93ce22df1fcddb5d34de8aed6dcf187e17e..4c9ab6a77af0118f190ace3e6d0a6685d9c40f56) of doing that.

**Pull request merged**
